### ISSUE TITLE
Onlyoffice integration with Nextcloud. Error Error while downloading the document file to be converted

### ISSUE THREAD

**Issue by Cyberknight234** [ONLYOFFICE/onlyoffice-nextcloud#127]
I had already looked around, but this couldn't solve my problem. I installed onlyoffice documents on another server.now i would like to use the addon in nextcloud. When I enter the serverip in Nextcloud, I get the following error: Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)

facts about my Systems:

Nextcloud(Nextcloud 16.0.4) -> OS Debian.
in the nextcloud config i also have " 'onlyoffice' =>array ( verify_peer_off' => TRUE, ) " added.

Onlyoffice(newest version) -> OS Ubuntu 18.04 LTS
Installed with this guide: https://helpcenter.onlyoffice.com/de/server/linux/document/linux-installation.aspx
Except for "Additional information" I did everything according to the instructions.

Called up via healthcheck I get a positive result.
I also have this error message under documentserver/converter/log .

[2019-08-29T16:29:49.962] [WARN] nodeJS - worker 11687 started.
[2019-08-29T16:29:49.963] [WARN] nodeJS - update cluster with 1 workers
[2019-08-29T16:40:12.293] [ERROR] nodeJS - error downloadFile:url=https://next.mydomain.xx/apps/onlyoffic ... TYdvdZNgMz$

Error: Parse Error
at TLSSocket.socketOnData (_http_client.js:454:20)
at emitOne (events.js:116:13) at TLSSocket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11)
at TLSSocket.Readable.push (_stream_readable.js:208:10)
at TLSWrap.onread (net.js:601:20)

What i have tried?
/etc/onlyoffice/documentserver/default.json change rejectUnauthorized to false but this doesn't solve the problem.
Firewall disabled.
Some other solutions.

I have read somewhere that the certificate of the document server must be installed on both servers. is this correct? if yes, do you have any instructions?
If anyone needs more configs or logs, please let me know.

**Comment by HelenBelova17** [comment]
Hello, @**Cyberknight234**, attach screenshot the page of Onlyoffice Server settings.

**Comment by Cyberknight234** [comment]
> 
> 
> Hello, @**Cyberknight234**, attach screenshot the page of Onlyoffice Server settings.

hello, thank you for your message. 

I only installed the document server. You can see some settings from my screenshots. I hope these are the settings you want. if not, I'll post them.

nginx/ds.conf:
include /etc/nginx/includes/http-common.conf;

## Normal HTTP host
server {
  listen 0.0.0.0:80;
  listen [::]:80 default_server;
  server_name office.mydomain.xx;
  server_tokens off;

  ## Redirects all traffic to the HTTPS host
  root /nowhere; ## root doesn't have to be a valid path since we are redire$
  rewrite ^ https://$host$request_uri? permanent;
}

#HTTP host for internal services
server {
  listen 127.0.0.1:80;
  listen [::1]:80;
  server_name office.mydomain.xx;
  server_tokens off;

  include /etc/nginx/includes/ds-common.conf;
  include /etc/nginx/includes/ds-docservice.conf;
}

## HTTPS host
server {
  listen 0.0.0.0:443 ssl;
  listen [::]:443 ssl default_server;
  server_tokens off;
  root /usr/share/nginx/html;

  ## Strong SSL Security
  ## https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
  ssl on;
  ssl_certificate /etc/letsencrypt/live/office.mydomain.xx-0001/fullchain.$
  ssl_certificate_key /etc/letsencrypt/live/office.mydomain.xx-0001/privke$
  ssl_verify_client off;

  ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

  ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
  ssl_session_cache  builtin:1000  shared:SSL:10m;

  ssl_prefer_server_ciphers   on;

  add_header Strict-Transport-Security max-age=31536000;
  # add_header X-Frame-Options SAMEORIGIN;
  add_header X-Content-Type-Options nosniff;

  ## [Optional] If your certficate has OCSP, enable OCSP stapling to reduce $
  ## Replace with your ssl_trusted_certificate. For more info see:
  ## - https://medium.com/devops-programming/4445f4862461
  ## - https://www.ruby-forum.com/topic/4419319
  ## - https://www.digitalocean.com/community/tutorials/how-to-configure-ocs$
  # ssl_stapling on;
  # ssl_stapling_verify on;
  # ssl_trusted_certificate /etc/nginx/ssl/stapling.trusted.crt;
  # resolver 208.67.222.222 208.67.222.220 valid=300s; # Can change to your $
  # resolver_timeout 10s;

  ## [Optional] Generate a stronger DHE parameter:
  ##   cd /etc/ssl/certs
  ##   sudo openssl dhparam -out dhparam.pem 4096
  ##
  # ssl_dhparam /etc/ssl/certs/dhparam.pem;
  include /etc/nginx/includes/ds-*.conf;
}

![githubNEXTCLOUD](https://user-images.githubusercontent.com/54815694/64176393-a8c0d180-ce5d-11e9-9956-00c6bc238274.PNG)
![githubLOCALJSON](https://user-images.githubusercontent.com/54815694/64176409-b0807600-ce5d-11e9-82ad-ab24baa6ecba.PNG)

**Comment by alexanderonlyoffice** [comment]
Hello @Cyberknight234, the error you get means that the document server cannot download the file from Nextcloud for conversion. 

Please specify some additional information about the problem:
1. What page in browser do you see when entering the address specified in the address settings of ONLYOFFICE integration app? Please send me a screenshot?
2. What SSL certificates do you use on both servers (ca-signed or self-signed)?
3. Please try to check the accessibility of the servers to each other. Execute the command `wget https://documentserver_address/` on the server with Nextcloud and `wget https://nextcloud_address/` on the server with Document Server.

**Comment by Cyberknight234** [comment]
thank you for your reply alex:=) 

1. 
When i open the address in my browser, i get the message "document server is running". you can find the picture below.
![GITHUBSCREENSHOT](https://user-images.githubusercontent.com/54815694/64195202-2f3ada80-ce81-11e9-930d-105f56ccabfb.PNG)

2.
I use an ssl certificate from letsencrypt for both nextcloud and document server.

3.
##Output from Nextcloud Server:
Resolving office.xyz.eu (office.xyz.eu)... 112.xx.x.xx
Connecting to office.xyz.eu (office.xyz.eu)|194.xx.xxx.xx|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://office.xyz.eu/welcome/ [following]
--2019-09-03 19:23:39--  https://office.xyz.eu/welcome/
Reusing existing connection to office.xyz.eu:443.
HTTP request sent, awaiting response... 200 OK
Length: 4592 (4.5K) [text/html]
Saving to: ‘index.html.1’

index.html.1        100%[================>]   4.48K  --.-KB/s    in 0s

2019-09-03 19:23:39 (98.1 MB/s) - ‘index.html.1’ saved [4592/4592]
##Output from Document Server:
--2019-09-03 19:26:38--  https://next.xyz.eu/
Resolving next.xyz.eu (next.xyz.eu)... 185.xxx.xxx.xxx
Connecting to next.xyz.eu (next.xyz.eu)|185.xxx.xxx.xxx|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://next.xyz.eu/login [following]
--2019-09-03 19:26:38--  https://next.xyz.eu/login
Reusing existing connection to next.xyz.eu:443.
HTTP request sent, awaiting response... 200 OK
Length: 7549 (7.4K) [text/html]
Saving to: ‘index.html.3’

index.html.3        100%[================>]   7.37K  --.-KB/s    in 0s

2019-09-03 19:26:39 (1.11 GB/s) - ‘index.html.3’ saved [7549/7549]
