### ISSUE TITLE
while starting onlyoffice docker - error downloadFile

### ISSUE THREAD

**Issue by Gollus** [ONLYOFFICE/onlyoffice-nextcloud#188]
Hello,
while starting onlyofficedocker I got the following error:
[2019-02-28T13:12:51.412] [ERROR] nodeJS - error downloadFile:url=https://xxx.xxx.xxx.xxx:4433/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.RD7_W06LPPrSfuPds0lmx-tshZeoXSmdaTsHKiqkL0I;attempt=3;code:null;connect:null;(id=conv_check_1850776178_docx)
Error: Error response: statusCode:404 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /apps/onlyoffice/empty</pre>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
Flushing stats at  Thu Feb 28 2019 13:18:58 GMT+0000 (UTC)
{ counters:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  timers: {},
  gauges: {},
  timer_data: {},
  counter_rates:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  sets: {},
  pctThreshold: [ 90 ] }

What's wrong?
Many thanks for your help!

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs?

**Comment by vinson0224** [comment]
My error is as follows: Upon inspection, it was found that there was an error in the time of two servers, nextcloud and only office. After synchronizing with NTP, it worked normally

[2024-04-24T02:22:34.764] [ERROR] [localhost] [conv_check_889245064_docx] [userId] nodeJS - error downloadFile:url=https://nextcloud.casetekcorp.com/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.0rdqDM8OV_BqQAIWIdDw96dxc1_fNUXOeuIcGI9cSwo;attempt=3;code:null;connect:null Error: Error response: statusCode:403; headers:{"date":"Wed, 24 Apr 2024 02:30:39 GMT","server":"Apache/2.4.57 (Rocky Linux) OpenSSL/3.0.7","x-powered-by":"PHP/8.1.27","expires":"Thu, 19 Nov 1981 08:52:00 GMT","pragma":"no-cache","x-request-id":"Zihuz7DCf216PaqX3HgyXAAAAAY","cache-control":"no-cache, no-store, must-revalidate","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","x-robots-tag":"noindex, nofollow","set-cookie":["oc_sessionPassphrase=mQYm%2BCzea8GR5qlihMAC8OxvXas2XU55IAjW8FP5g3HIiBYE3XvZtRjhBH7mykswu51%2B2EMVEnaBIt2RFnnRhkQtJGgYZZN9kcAkpOSG6Kwd1mmhqBoOL6BM%2F%2Ful6Z48; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","ocb012micklv=2q6ue0lbqnlgvr79oc9tu6vp6s; path=/; secure; HttpOnly; SameSite=Lax"],"referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"1; mode=block","content-length":"27","keep-alive":"timeout=5, max=100","connection":"Keep-Alive","content-type":"application/json; charset=utf-8"};
    at Request.fResponse (/snapshot/server/Common/sources/utils.js)
    at Request.emit (node:events:527:28)
    at Request.onRequestResponse (/snapshot/server/Common/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by LinneyS** [comment]
@vinson0224 this is normal, because in JWT uses a timestamp

**Comment by LinneyS** [comment]
This issue was closed due to no response.

**Comment by Liionboy** [comment]
How is normal if we can't configure Nextclooud:

Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 8.1.1.26)

Is not normal this error
