### ISSUE TITLE
Faulty callback, no modification timestamp in NC

### ISSUE THREAD

**Issue by pi-xel** [ONLYOFFICE/onlyoffice-nextcloud#197]
Hi,

First off, thanks for the great work on OnlyOffice integration in Owncloud/Nextcloud.

I have compiled latest OnlyOffice GIT clone on an Arm (yes, that's possible, see here https://github.com/ONLYOFFICE/DocumentServer/issues/152, my server is an ODroid XU4 running Debian Jessie) and am running Nextcloud 12.0.1 on it, with latest OnlyOffice integration 1.1.3. I am running OnlyOffice server on HTTPS and without a secret.

Everything is working well, I can create new files, edit existing ones and save them.

However, I have two issues:

1. The callback does not seem to work properly. Whenever I finish editing a document, after 10 seconds the following messages appear in my Nextcloud log:
```
Error	onlyoffice	GetConvertedUri in track: Error occurred in the document service: Unknown error
Error	PHP	Undefined index: extension at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#127
```
Apparently, the $document_uri variable is empty there.

Because the document extension cannot be extracted from the empty URI, also OnlyOffice File Converter logs an error such as:
```
[2017-08-13 11:08:21.310] [ERROR] nodeJS - stderr (id=9481851502610297_6540):
[2017-08-13 11:08:21.311] [ERROR] nodeJS - ExitCode (code=0;signal=SIGSEGV;error:-80;id=9481851502610297_6540)
```
And also in document server log the following error appears:
```
[2017-08-13 11:08:22.903] [ERROR] nodeJS - sendServerRequest error: docId = 9481851502610297;url = https://nextcloud.example.com/index.php/apps/onlyoffice/track?doc=RzFXbmluY1d3MFJqWXZtVVh3VjhIWEJLWHNtamhnb2tWbWRyRGl3d1RjYz0/eyJmaWxlSWQiOjk0ODE4NSwib3duZXJJZCI6InBoaWwiLCJhY3Rpb24iOiJ0cmFjayJ9;data = {"key":"9481851502610297","status":3,"users":["xxxx"],"actions":[{"type":0,"userid":"xxxx"}],"lastsave":"2017-08-13T09:08:06.304Z","notmodified":false}
Error: Error response: statusCode:500 ;body:
{"message":"Error occurred in the document service: Unknown error"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:269:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

2. For some reason (maybe related to 1.), edits are not saved in Nextcloud, i.e. when I create a document and edit it thereafter, the last modification shown in Nextcloud is still shown as the creation time.

3. ~~I can only edit docx, pptx and xlsx files, not doc, xls, ppt and no open document formats. For these file types, the download dialog is opened. I don't know whether it's supposed to be like this, but I thought that the File Converter part of OnlyOffice should be able to handle these types.~~ Edit: Just saw that there's a menu item to convert from e.g. odt to docx for editing. This works well.

Please help to resolve these issues. If needed, I would be happy to provide more logs and trace variables.

Best regards,
pi-xel

**Comment by LinneyS** [comment]
This issue was closed due to no response.

**Comment by xiaobing395845388** [comment]
hi  ,can your doucumentserver work on arm ?,can you share your docker image ? thank you
