### ISSUE TITLE
cannot loading file larger 5MB

### ISSUE THREAD

**Issue by olivy70** [ONLYOFFICE/onlyoffice-nextcloud#269]
Hi,
My environnement :
Unbuntu 16.04 TLS
PHP7/Nginx
Nextcloud 16
onlyoffice/documentserver last docker version
Installation guide from https://riegers.in/nextcloud-and-only-office-nginx/

The problem appears for files larger than 5MB.

Here is the out.log
==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2020-03-24T08:28:12.961] [ERROR] nodeJS - error downloadFile:url=https://MYURL/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjQ0MDk0NCwidXNlcklkIjoib2xpdmllci5wcmFkaWVyIiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.GYRae6RvXNCRDjacKQ4DZEsl68BAD8wke42CtRbtNnk;attempt=1;code:ESOCKETTIMEDOUT;connect:false;(id=2550348282)
Error: ESOCKETTIMEDOUT
at ClientRequest. (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
at Object.onceWrapper (events.js:286:20)
at ClientRequest.emit (events.js:198:13)
at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
at Object.onceWrapper (events.js:286:20)
at TLSSocket.emit (events.js:198:13)
at TLSSocket.Socket._onTimeout (net.js:443:8)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)

A little help ?
Thanks !

**Comment by olivy70** [comment]
@ShockwaveNN 
for information, i have not the problem with COLLABORA.
Thanks !

**Comment by acsfer** [comment]
Please note we have similar problem with v6.3.1 Entreprise Edition

```
[ERROR] nodeJS - sendServerRequest error: docId = 4105671099;url = https://cloud.example/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJzYWJyaW5lLnJlemtpQGFsaXhpYXN1cHBvcnQuZnIiLCJmaWxlSWQiOjU2MjAyMDE3LCJmaWxlUGF0aCI6IlwvUGFydGFnZSBSZWNydXRlbWVudFwvVEFCTEVBVVggREUgU1VJVklTXC9Db3BpZSBkZSBUYWJsZWF1IFNCSCAyLnhsc3giLCJzaGFyZVRva2VuIjpudWxsLCJhY3Rpb24iOiJ0cmFjayJ9.lZaoWspwR5GVIiNTuoTTb6bOL5Oh6O_bIZbOIzhTF4M;data = {"key":"4105671099","status":6,"url":"https://onlyoffice.cloud.example/cache/files/4105671099_9952/output.xlsx/output.xlsx?md5=l6QsITk6zGaiOyXE-6DAjQ&expires=1629279520&disposition=attachment&filename=output.xlsx","changesurl":"https://onlyoffice.cloudeezy.com/cache/files/4105671099_9952/changes.zip/changes.zip?md5=VXoQPc-d984VmZjtQxuT8Q&expires=1629279520&disposition=attachment&filename=changes.zip","history":{"serverVersion":"6.3.2","changes":[{"created":"2021-08-18 08:00:27","user":{"id":"oc6xz1h8l8n2_sabrine.rezki@cloud.example","name":"Sabrine REZKI"}}]},"users":["oc6xz1h8l8n2_sabrine.rezki@cloud.example"],"actions":[{"type":2,"userid":"oc6xz1h8l8n2_sabrine.rezki@cloud.example"}],"lastsave":"2021-08-18T09:23:33.000Z","forcesavetype":1}
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by mbx2015** [comment]
We have the same problem with 7.1.0. 
What is strange is that the issue goes when the server have access to internet connection, but when I remove connection I got the same error again.
