### ISSUE TITLE
Onlyoffice speichert Datein nicht in Nextcloud (NX:V18 OO:4.1.4)

### ISSUE THREAD

**Issue by YKiessling** [ONLYOFFICE/onlyoffice-nextcloud#282]
Es ist das selbe Problem wie im untern Bug - nur das dieser mit NX18 und ohne externe Speicher auftitt (war das Problem nicht mal behoben?).

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/118#issuecomment-522981312

ist da ein Problem bereits bekannt? 

Gruß
 YK

**Comment by sargreal** [comment]
Have the same Problem using 
- Nextcloud 18.0.4
- onlyoffice plugin 4.1.4
- onlyoffice/documentserver 5.5 (docker)

Stacktrace:
```
Error: Error response: statusCode:307 ;body:
Temporary Redirect
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by sargreal** [comment]
Have fixed the issue for me. Problem was that by default internal requests were sent over http and these were redirected to https which the documentserver didn't like
