### ISSUE TITLE
Nextcloud + docker onlyoffice : cannot loading file larger 5MB

### ISSUE THREAD

**Issue by olivy70** [ONLYOFFICE/onlyoffice-nextcloud#313]
Hi,
My environnement :
Unbuntu 16.04 TLS
PHP7/Nginx
Nextcloud 16
onlyoffice/documentserver last docker version
Installation guide from https://riegers.in/nextcloud-and-only-office-nginx/

The problem appears for files larger than 5MB.

Here is the out.log
==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2020-03-24T08:28:12.961] [ERROR] nodeJS - error downloadFile:url=https://MYURL/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjQ0MDk0NCwidXNlcklkIjoib2xpdmllci5wcmFkaWVyIiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.GYRae6RvXNCRDjacKQ4DZEsl68BAD8wke42CtRbtNnk;attempt=1;code:ESOCKETTIMEDOUT;connect:false;(id=2550348282)
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

A little help ?
Thanks !

**Comment by LinneyS** [comment]
#269
