### ISSUE TITLE
[ERROR] nodeJS - error downloadFile -  statusCode:403

### ISSUE THREAD

**Issue by jsalatiel** [ONLYOFFICE/onlyoffice-nextcloud#344]
I've been testing only office + nextcloud for a couple of weeks flawless. Yesterday, it suddenly stopped working complaining that it could not save files. I tried restarting the containers, and then I tried to disable and re-enable the onlyoffice nextcloud app, but now i can not even save the connector configuration anymore. I get:

_Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 5.5)✖_

Nothing is showed on the onlyoffice/communityserver:10.5.3.1172 container log, but in the onlyoffice/documentserver:5.5.3.39 container log I can see:
```
[2020-08-26T12:22:22.585] [ERROR] nodeJS - error downloadFile:url=https://nextcloud.my.domain.here/index.php/apps/onlyoffice/empty?doc=obfuscated.obfuscated-w;attempt=1;code:null;connect:null;(id=conv_check_291727847_docx)
Error: Error response: statusCode:403 ;body:
{"message":"Acesso negado"}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-08-26T12:22:23.691] [ERROR] nodeJS - error downloadFile:url=https://nextcloud.my.domain.here/index.php/apps/onlyoffice/empty?doc=obfuscated.obfuscated-w;attempt=2;code:null;connect:null;(id=conv_check_291727847_docx)
Error: Error response: statusCode:403 ;body:
{"message":"Acesso negado"}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-08-26T12:22:24.750] [ERROR] nodeJS - error downloadFile:url=https://nextcloud.my.domain.here/index.php/apps/onlyoffice/empty?doc=obfuscated.obfuscated-w;attempt=3;code:null;connect:null;(id=conv_check_291727847_docx)
Error: Error response: statusCode:403 ;body:
{"message":"Acesso negado"}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
{"message":"Acesso negado"} means "Access Forbidden". it is in Portuguese because our instance runs in Portuguese as default language.

I am usually really skeptical when saying that nothing has changed, but in this case nothing has changed in our setup.

Nextcloud 18.0.6
OnlyOffice Connector ( Nextcloud app ) 4.3.0
onlyoffice/communityserver:10.5.3.1172 / onlyoffice/documentserver:5.5.3.39 ( docker )

**Comment by jsalatiel** [comment]
The problem was the clock was 5 seconds behind and the token was being rejected.
