### ISSUE TITLE
Nextcloud Integration <> onlyoffice 5.5 -> Download errors when using JWT token

### ISSUE THREAD

**Issue by LKNickname** [ONLYOFFICE/onlyoffice-nextcloud#345]
NC Version: 18.0.7
OO Version: 5.5.3.39
OO NC App Version: 4.3.0

Hey all!

Whenever I try to setup the OOxNC integration I receive the following error:
_Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 5.5)_

That error only occurs when I am using JWT tokens through the OO local.json.
If I disable the usage of tokens the connection works fine.
A simple wget works in both directions without errors (OO -> NC & NC -> OO).

What caught me off guard is that it has been working for quite a while now (using tokens) and after updating OO or NC (can't remember which one though) it suddenly stopped working altogether.

Reinstalling OO does not solve the problem.

Below you will find the relevant contents of my local.json as well as the output of "/var/log/onlyoffice/documentserver/converter/out.log"
Note: I did not change anything in the default.json

**local.json**
`
      "token": {
        "enable": {
          "request": {
            "inbox": true,
            "outbox": true
          },
          "browser": true
        },
        "inbox": {
          "header": "Authorization"
        },
        "outbox": {
          "header": "Authorization"
        }
      },
      "secret": {
        "inbox": {
          "string": "MYSECRETKEY"
        },
        "outbox": {
          "string": "MYSECRETKEY"
        },
        "session": {
          "string": "MYSECRETKEY"
        }
      }
    }
  },
`

**out.log**
`Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

Any ideas?

Edit (because I forgot to mention):
Adding `"‘onlyoffice’ => array (
‘verify_peer_off’ => true
)` within the NC config.php does not fix the issue.

**Comment by LinneyS** [comment]
Hi @LKNickname 
Try changing the header:
DocumentServer - `"inbox": { "header": "Authorization2" }, "outbox": { "header": "Authorization2" } `
Nextcloud - `"onlyoffice" => array ( "jwt_header" => "Authorization2" )`

**Comment by LKNickname** [comment]
I changed the config values within local.json (ds) and added them within the nextcloud config.php respectively but sadly I receive the same error message as before.

**Comment by LKNickname** [comment]
Quick Update:
Upgraded Onlyoffice to version 5.6.3.2 and Nextcloud to 19.0.3, error is still there.

I tried your solution again after updating but I receive the same error message as before.
In addition to that I tried the solution mentioned in #153 again -> same result...running out of ideas here 😅

**Comment by LKNickname** [comment]
Any updates? It's kinda important

**Comment by ibnpetr** [comment]
Do you have any proxy server between your NC and OO ?
The issue may be in the lost header.

**Comment by LKNickname** [comment]
Nextcloud is not behind a proxy but now that you mention it...
I installed Onlyoffice using UCS which put's it in a docker container - Not sure if it is behind a proxy though as it worked just fine for months before suddenly throwing the error.

In case it is behind a proxy:
Do I just need to preserve the header or is there anything else I need to check while I am at it?

**Comment by tspaeth** [comment]
I'm currently trying to setup nextcloud <-> onlyoffice docker daemon and struggled with this "access denied" error. As I've got still another issue with 404 - errors on the empty test file, I've tracked down this Access denied error to an issue on the JWT-Comparison and timestamps. 
As both servers are "separate", there might be milliseconds here so that the calling side is newer than the server thinks it is.
Therefore the comparison in 3rdparty/jwt/JWT.php fails "sometimes"... (L114) ... I've not used the toolings before, but isn't this already one of the solutions to reduce issues? :)
