### ISSUE TITLE
Nextcloud app won't use jwt_secret

### ISSUE THREAD

**Issue by zingmars** [ONLYOFFICE/onlyoffice-nextcloud#47]
After updating to the latest onlyoffice docker, I can't seem to get any connection to it from Nextcloud. I can access it from the browser, but when trying to connect to it from nextcloud I get

```
{"reqId":"1XkYs4VQGhXTJPV3ZZkF","level":3,"time":"2018-11-15T14:01:12+00:00","remoteAddr":"internal-ip","user":"--","app":"onlyoffice","method":"GET","url":"\/apps\/onlyoffice\/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.dzGbTTowX_dLViEYKGyYN9oHW9oXPBr-IiwOyv0OtEc","message":"Download empty without jwt","userAgent":"--","version":"14.0.3.0"}
{"reqId":"x34OZ0ymJPY86Tg5SdLw","level":3,"time":"2018-11-15T14:01:13+00:00","remoteAddr":"internal-ip","user":"--","app":"onlyoffice","method":"GET","url":"\/apps\/onlyoffice\/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.dzGbTTowX_dLViEYKGyYN9oHW9oXPBr-IiwOyv0OtEc","message":"Download empty without jwt","userAgent":"--","version":"14.0.3.0"}
{"reqId":"ehm4C3KAMs1jfqkUbIaN","level":3,"time":"2018-11-15T14:01:14+00:00","remoteAddr":"internal-ip","user":"--","app":"onlyoffice","method":"GET","url":"\/apps\/onlyoffice\/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.dzGbTTowX_dLViEYKGyYN9oHW9oXPBr-IiwOyv0OtEc","message":"Download empty without jwt","userAgent":"--","version":"14.0.3.0"}
{"reqId":"vxDMR3EKLvDKv74wiA2r","level":3,"time":"2018-11-15T14:01:16+00:00","remoteAddr":"external-ip","user":"zingmars","app":"onlyoffice","method":"PUT","url":"\/apps\/onlyoffice\/ajax\/settings","message":"GetConvertedUri on check error: Error occurred in the document
service: Error while downloading the document file to be converted.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
```
The thing is, I already have the following lines in the `config.php` - 
```
'onlyoffice' =>
  array (
   'verify_peer_off' => true,
   "jwt_secret" => "<>",
   "jwt_header" => "<>",
  ),
```
I also set the secret key field in the settings. 
Server side I get this

```
onlyoffice_1  | [2018-11-15 14:01:14.638] [ERROR] nodeJS - error downloadFile:url=https://domain/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.dzGbTTowX_dLViEYKGyYN9oHW9oXPBr-IiwOyv0OtEc;attempt=3;code:undefined;connect:undefined;(id=conv_check_98850012_docx)
onlyoffice_1  | Error: Error response: statusCode:403 ;body:
onlyoffice_1  | {"message":"Access denied"}
onlyoffice_1  |     at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
onlyoffice_1  |     at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
onlyoffice_1  |     at emitTwo (events.js:126:13)
onlyoffice_1  |     at Request.emit (events.js:214:7)
onlyoffice_1  |     at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
onlyoffice_1  |     at emitOne (events.js:116:13)
onlyoffice_1  |     at Request.emit (events.js:211:7)
onlyoffice_1  |     at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
onlyoffice_1  |     at Object.onceWrapper (events.js:313:30)
onlyoffice_1  |     at emitNone (events.js:111:20)
```

**Comment by zingmars** [comment]
Apparently the container now ignores the environment values, and no longer accepts settings from `default.json` and uses `local.json` instead (which wasn't really documented anywhere) as I found out here - https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/137.  It started to work properly after I moved all my settings to the `local.json` file. I guess I forgot to update this issue.
