### ISSUE TITLE
Error connecting Nextcloud to OnlyOffice

### ISSUE THREAD

**Issue by apritcha1** [ONLYOFFICE/onlyoffice-nextcloud#472]
Hello, I am writing this issue to see if anyone has any ideas regarding my problem with Nextcloud and OnlyOffice.
When trying to connect to OnlyOffice via NextCloud, I get the error "Error occurred in the document service: Error while downloading the document file to be converted."

Nextcloud is running on an Ubuntu VM on https://subdomain.domain.com, and OnlyOffice is running in a Debian VM at https://subdomain.domain.com:10443
Both VMs are behind an HAProxy reverse proxy installed on a third VM running OPNsense. Header forwarding should be working as specified in the documentation (https://helpcenter.onlyoffice.com/de/installation/docs-community-proxy.aspx). 

Both VMs can wget each other: (domains and IPs replaced)
Nextcloud:
```wget https://subdomain.domain.com:10443/welcome/
--2021-05-17 15:19:15--  https://subdomain.domain.com:10443/welcome/
Resolving subdomain.domain.com (subdomain.domain.com)... 000.000.000.000
Connecting to subdomain.domain.com (subdomain.domain.com)|000.000.000.000|:10443... connected.
HTTP request sent, awaiting response... 200 OK
```
OnlyOffice:
```wget https://subdomain.domain.com/login
--2021-05-17 15:21:39--  https://subdomain.domain.com/login
Resolving subdomain.domain.com (subdomain.domain.com)... 000.000.000.000
Connecting to subdomain.domain.com (subdomain.domain.com)|000.000.000.000|:443... connected.
HTTP request sent, awaiting response... 200 OK
```
OnlyOffice welcome page works fine. 

In the FileConverter output, the following is found:
```
[2021-05-17T14:47:31.191] [ERROR] nodeJS - error downloadFile:url=https://subdomain.domain.com:10443/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.e85ySZWSNrHWYHvKr7YnUekD5JwkZcjqya-ZETu3H5w;attempt=3;code:null;connect:null;(id=conv_check_1524965790_docx)
Error: Error response: statusCode:404 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /apps/onlyoffice/empty</pre>
</body>
</html>

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Not sure where to go from here, any help would be appreciated. If any more information is required please let me know.

**Comment by agolybev** [comment]
Hi @apritcha1, try using ONLYOFFICE Docs on the standard port, Document Server can run behind a proxy but I'm not sure the same about ONLYOFFICE Docs Example.
