### ISSUE TITLE
Exception since upgrade to PHP 8

### ISSUE THREAD

**Issue by leuedaniel** [ONLYOFFICE/onlyoffice-nextcloud#490]
Since i've upgraded to php8.0 i've problems with onlyoffice. 

Error message: Exception: Im Dokumentenservice ist ein Fehler aufgetreten: Error while downloading the document file to be converted.

**Operating system:** Ubuntu 20.04.2

**Web server:** nginx/1.18.0

**Database:** MariaDB 10.4.14

**PHP version:** 8.0.7

**Nextcloud version:**  21.0.2

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>
<html>
<body>

Exception: Im Dokumentenservice ist ein Fehler aufgetreten: Error while downloading the document file to be converted./var/www/html/apps/onlyoffice/lib/documentservice.php - line 94:OCA\Onlyoffice\DocumentService->ProcessConvServResponceError()/var/www/html/apps/onlyoffice/lib/preview.php - line 267:OCA\Onlyoffice\DocumentService->GetConvertedUri()/var/www/html/lib/private/Preview/ProviderV1Adapter.php - line 54:OCA\Onlyoffice\Preview->getThumbnail()/var/www/html/lib/private/Preview/GeneratorHelper.php - line 63:OC\Preview\ProviderV1Adapter->getThumbnail()/var/www/html/lib/private/Preview/Generator.php - line 244:OC\Preview\GeneratorHelper->getThumbnail()/var/www/html/lib/private/Preview/Generator.php - line 140:OC\Preview\Generator->getMaxPreview()/var/www/html/lib/private/Preview/Generator.php - line 109:OC\Preview\Generator->generatePreviews()/var/www/html/lib/private/PreviewManager.php - line 190:OC\Preview\Generator->getPreview()/var/www/html/core/Controller/PreviewController.php - line 170:OC\PreviewManager->getPreview()/var/www/html/core/Controller/PreviewController.php - line 143:OC\Core\Controller\PreviewController->fetchPreview()/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 218:OC\Core\Controller\PreviewController->getPreviewByFileId()/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 127:OC\AppFramework\Http\Dispatcher->executeController()/var/www/html/lib/private/AppFramework/App.php - line 157:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/html/lib/private/Route/Router.php - line 302:OC\AppFramework\App::main()/var/www/html/lib/base.php - line 993:OC\Route\Router->match()/var/www/html/index.php - line 37:OC::handleRequest()
--

</body>
</html></summary>

**Comment by SergeyKorneyev** [comment]
Hello,
The log does not contain any errors linked to PHP, and the issue is most likely caused by an incorrect editors integration. Please make sure that the Document Server has access to Nextcloud and vice versa.

**Comment by leuedaniel** [comment]
I have had this error message since the update to php8.0.7 before I did not have this error message. Nextcloud and onlyoffice run on the same server. onlyoffice as docker. onlyoffice works perfectly but I always get these error messages.

**Comment by SergeyKorneyev** [comment]
Please try checking the Document Server logs. The **out.log** file from the Converter and/or Docservice folder should contain the error which can explain why documents fail to be downloaded.

**Comment by leuedaniel** [comment]
#### Converter out.log
<details>
<summary>Converter out.log</summary>

```
[2021-06-23T17:40:09.526] [ERROR] nodeJS - error downloadFile:url=https://cloud.ehv.ch/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ>
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2021-06-23T17:40:19.546] [ERROR] nodeJS - error downloadFile:url=https://cloud.ehv.ch/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ>
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2021-06-23T17:40:29.586] [ERROR] nodeJS - error downloadFile:url=https://cloud.ehv.ch/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ>
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2021-06-23T17:40:39.612] [ERROR] nodeJS - error downloadFile:url=https://cloud.ehv.ch/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ>
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

```
</details>

#### Docservice out.log
<details>
<summary>Docservice out.log</summary>

```
[2021-06-23T15:19:47.558] [WARN] nodeJS - Express server starting...
[2021-06-23T15:19:47.560] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2021-06-23T15:19:47.580] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.3.1. Build: 32
[2021-06-23T15:20:17.397] [WARN] nodeJS - Express server starting...
[2021-06-23T15:20:17.399] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2021-06-23T15:20:17.417] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.3.1. Build: 32
[2021-06-23T17:38:11.844] [WARN] nodeJS - error description: docId = 693437225 errorId = Update Version error

```
</details>

**Comment by SergeyKorneyev** [comment]
According to the logs, the Document Server cannot connect to the Nextcloud instance to download files. You need to check if the https://***/ address is reachable from the Document Server's container
