### ISSUE TITLE
File content update by onlyoffice not sync back to nextcloud server

### ISSUE THREAD

**Issue by kyhuynhduc** [ONLYOFFICE/onlyoffice-nextcloud#516]
Dear team,
our system was 
1.nextcloud 21.0.4 +
2.onlyoffice-nextcloud version 7.1.2
3.onlyoffice document server community 6.4.0.121

connection look like good as screen bellow

![image](https://user-images.githubusercontent.com/36893030/131353412-17ea4d95-490f-4bb9-832d-538e9f967b22.png)

then we facing with issues:
- user open file => update content => save => close browser tab
- user re-reopen file => content still available 
- user download file to local computer => open with MS word => content not available 

![image](https://user-images.githubusercontent.com/36893030/131356386-84bf76ee-5b1e-4aab-bb3d-6cbc10bb4956.png)

please help.

## document server log file as bellow:
/var/log/onlyoffice/documentserver/nginx.error.log
-----------
`/var/www/onlyoffice/documentserver/sdkjs/common/libfont/wasm/manager.js" failed (2: No such file or directory), client: 10.1.5.64, server: only-office.xxxx.vn, request: "GET /sdkjs/common/libfont/wasm/manager.js HTTP/1.1", host: "only-office.xxxx.vn", referrer: "https://only-office.itmwg.vn/web-apps/apps/api/documents/cache-scripts.html`
```
2021/08/30 11:40:45 [error] 1272320#1272320: *1298 open() "/var/www/onlyoffice/documentserver/sdkjs/common/libfont/wasm/file.js" failed (2: No such file or directory), client: 10.1.5.64, server: only-office.xxxx.vn, request: "GET /sdkjs/common/libfont/wasm/file.js HTTP/1.1", host: "only-office.xxxx.vn", referrer: "https://only-office.xxxx.vn/web-apps/apps/api/documents/cache-scripts.html"
2021/08/30 11:40:45 [error] 1272320#1272320: *1299 open() "/var/www/onlyoffice/documentserver/sdkjs/common/libfont/wasm/engine.js" failed (2: No such file or directory), client: 10.1.5.64, server: only-office.xxx.vn, request: "GET /sdkjs/common/libfont/wasm/engine.js HTTP/1.1", host: "only-office.itmwg.vn", referrer: "https://only-office.xxxx.vn/web-apps/apps/api/documents/cache-scripts.html
```

/var/log/onlyoffice/documentserver/docservice/out.log
```
[2021-08-30T12:38:13.925] [WARN] nodeJS - storeForgotten: docId = 1914291621
[2021-08-30T13:08:28.013] [ERROR] nodeJS - sendServerRequest error: docId = 2322097523;url = https://docs.xxxx.vn/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxMjg3NjkiLCJmaWxlSWQiOjEwMjA2MzEsImZpbGVQYXRoIjoiXC8wOS1SRVctVGhcdTAxYjBcdTFlZGZuZyBuXHUxZWQ5aSBiXHUxZWQ5XC8wOS1SRVdfQkhYX1RodW9uZyB0cmFjaCBuaGllbSBCSFhcL1JXX0JIWF9UaHVvbmdUcmFjaE5oaWVtLmRvY3giLCJzaGFyZVRva2VuIjpudWxsLCJhY3Rpb24iOiJ0cmFjayJ9.4bndoqSU33bIEzCKCDT7lp2RXrfYVyayLaguprwzi7Y;data = {"key":"2322097523","status":2,"url":"https://only-office.xxxx.vn/cache/files/2322097523_1427/output.docx/output.docx?md5=ZjJqXkbwTpjFGDH5XfITUw&expires=1630304608&filename=output.docx","changesurl":"https://only-office.xxxx.vn/cache/files/2322097523_1427/changes.zip/changes.zip?md5=7zOMKNYFYTVukQus3Sdkiw&expires=1630304608&filename=changes.zip","history":{"serverVersion":"6.4.0","changes":[{"created":"2021-08-30 03:56:41","user":{"id":"ocwrrh4hl8tx_128769","name":"Nguyễn Hồng Sơn"}}]},"users":["ocwrrh4hl8tx_128769"],"actions":[{"type":0,"userid":"ocwrrh4hl8tx_128769"}],"lastsave":"2021-08-30T04:36:31.000Z","notmodified":false}
Error: Error response: statusCode:403; headers:{"server":"nginx/1.18.0 (Ubuntu)","date":"Mon, 30 Aug 2021 06:08:28 GMT","content-type":"application/json; charset=utf-8","content-length":"27","expires":"Thu, 19 Nov 1981 08:52:00 GMT","pragma":"no-cache","set-cookie":["oc_sessionPassphrase=0zfvx7SzqclkpfoIwYEv7lx0lDtd5IKWwgGIGqWHuBUGCebVYhrn0viKVdwvYuxyzN%2FcDZQ9Ik1yBpVdLLyYDC5HtDhpI8xm1S5mZ2UiNnGIiUnYiX6IPOWLaIjCVp03; path=/; secure; HttpOnly; SameSite=Lax","oc29b9aj4tur=pob2eud49643o991nrrcvdvvla; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","SvID=c6221|YSx13|YSx13; path=/"],"cache-control":"no-cache, no-store, must-revalidate","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","x-robots-tag":"none, none","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"1; mode=block","strict-transport-security":"max-age=31536000; preload;"}; body:
{"message":"Access denied"}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2021-08-30T13:08:28.017] [WARN] nodeJS - storeForgotten: docId = 2322097523
[2021-08-30T17:25:57.931] [WARN] nodeJS - checkJwt error: docId = 10.152.254.82__10.1.5.64https___only-office.xxx.vn_example_files_10.152.254.82__10.1.5.64_new.docx1630319156645 name = JsonWebTokenError message = jwt must be provided token = 
[2021-08-30T17:26:49.095] [WARN] nodeJS - checkJwt error: docId = 10.152.254.82__10.1.5.64https___only-office.xxxx.vn_example_files_10.152.254.82__10.1.5.64_new.docx1630319156645 name = JsonWebTokenError message = jwt must be provided token = 
[2021-08-30T17:41:47.089] [WARN] nodeJS - checkJwt error: docId = 10.152.254.82__10.1.5.64https___only-office.xxx.vn_example_files_10.152.254.82__10.1.5.64_new_20_1_.docx1630320105883 name = JsonWebTokenError message = jwt must be provided token = 
```

**Comment by LinneyS** [comment]
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository. 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by kyhuynhduc** [comment]
> Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository.
> 
> If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://forum.onlyoffice.com/t/community-document-server-app-in-nextcloud-18/268).

thank for your information.
a littlebit confuse that i was setup onlyoffice-connector version 7.1.2 ? 
![image](https://user-images.githubusercontent.com/36893030/132732971-2b50adcf-aa2b-4962-adf5-56fbdf40a37f.png)

**Comment by SergeyKorneyev** [comment]
Hello @kyhuynhduc,
The connector app is used to the integrate the Document Server (which should also be installed separately) with your Nextcloud instance. Could you specify how exactly you've installed the Document Server?

**Comment by petronem** [comment]
i'm confused as well. after experiencing some data loss w/ the NC OO thing, i read through all this and went to go run OO w/ docker...but then i read this:
https://github.com/ONLYOFFICE/Docker-DocumentServer#document-server-usage-issues
![image](https://user-images.githubusercontent.com/22941760/132879486-9278c09b-4082-4586-9e5b-0e3f27f36fe1.png)
or do the crontabs w/in the OO docker image take care of the flushing? if so how often?

**Comment by kyhuynhduc** [comment]
> Hello @kyhuynhduc,
> The connector app is used to the integrate the Document Server (which should also be installed separately) with your Nextcloud instance. Could you specify how exactly you've installed the Document Server?

Dear @SergeyKorneyev 
we install document server as command bellow:
=======
sudo apt update		
sudo apt upgrade

sudo apt install nodejs

sudo apt-get install postgresql 
sudo -i -u postgres psql -c "CREATE DATABASE onlyoffice;"
sudo -i -u postgres psql -c "CREATE USER onlyoffice WITH password 'onlyoffice';"
sudo -i -u postgres psql -c "GRANT ALL privileges ON DATABASE onlyoffice TO onlyoffice;"

sudo apt-get install rabbitmq-server

sudo apt-get install nginx-extras

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
echo "deb https://download.onlyoffice.com/repo/debian squeeze main" | sudo tee /etc/apt/sources.list.d/onlyoffice.list
sudo apt-get update

sudo apt-get install ttf-mscorefonts-installer

sudo apt-get install onlyoffice-documentserver

supervisorctl restart all
supervisorctl status all

========
check connection from nextcloud:
<img width="1131" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/36893030/133307537-70947fca-aaf0-4685-95b9-e166a34a197c.png">

**Comment by SergeyKorneyev** [comment]
@kyhuynhduc 
Please try changing the JWT header in both Nextcloud's **config.php** and Document Server's **local.json** from "Authorization" to "AuthorizationJwt" to see if that works.
