### ISSUE TITLE
Access Onlyoffice from outside local LAN

### ISSUE THREAD

**Issue by benjelloun69** [ONLYOFFICE/onlyoffice-nextcloud#56]
Hello everybody,
I will try to be short.
My config : 
- 2 servers A and B in different cities.
- Server A configured/working well : Nextcloud/onlyoffice both HTTPS & have domains => www.mynextcloud.com & www.onlyofficeserver.com.
- Server B is a replication of server A : MySQL with GTID Replication AND Nextcloud Directory with inotify & Rsync for Replication.
- Onlyoffice is only installed in server A.
- Server B is working well but onlyoffice error : 
![capture](https://user-images.githubusercontent.com/16430387/51206183-c6115180-1907-11e9-8ede-7ad25da3ded1.PNG)

{"reqId":"QJX1OubCPYfcPTmvM5yg","level":3,"time":"2019-01-15T18:44:47+00:00","remoteAddr":"<hidden>","user":"root","app":"onlyoffice","method":"PUT","url":"\/index.php\/apps\/onlyoffice\/ajax\/settings","message":"GetConvertedUri on                                                                                                                          check error: Une erreur s'est produite dans le service de document: Error while downloading the document file to be converted.","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.                                                                                                                         3578.98 Safari\/537.36","version":"15.0.0.10"}

I have already edited :
"rejectUnauthorized": false (in default.json)

'onlyoffice' =>
  array (
    'verify_peer_off' => true,
    "jwt_secret" => "secret", (obtained in default.json)
    "jwt_header" => "Authorization" (obtained in default.json)
  )
(in config.php)

Nextcloud version 'version' => '15.0.0.10'

Thank you in advance for your help.

I have just checked "converter" log : 

[2019-01-15 21:37:37.734] [DEBUG] nodeJS - Start Task(id=conv_check_1947642080_docx)
[2019-01-15 21:37:37.964] [ERROR] nodeJS - error downloadFile:url=https://<hidden>/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.zf5l2Biyy0f6P3U72pUxqfuQQbbwJHHgBTJ70yNKqm0;attempt=1;code:undefined;connect:undefined;(id=conv_check_1947642080_docx)
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
[2019-01-15 21:37:39.125] [ERROR] nodeJS - error downloadFile:url=https://<hidden>/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.zf5l2Biyy0f6P3U72pUxqfuQQbbwJHHgBTJ70yNKqm0;attempt=2;code:undefined;connect:undefined;(id=conv_check_1947642080_docx)
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
[2019-01-15 21:37:40.294] [ERROR] nodeJS - error downloadFile:url=https://<hidden>/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.zf5l2Biyy0f6P3U72pUxqfuQQbbwJHHgBTJ70yNKqm0;attempt=3;code:undefined;connect:undefined;(id=conv_check_1947642080_docx)
Error: Error response: statusCode:403 ;body:
{"message":"Access denied"}
    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
[2019-01-15 21:37:41.295] [DEBUG] nodeJS - ExitCode (code=0;signal=null;error:-81;id=conv_check_1947642080_docx)
[2019-01-15 21:37:41.298] [DEBUG] nodeJS - output (data={"cmd":{"c":"conv","id":"conv_check_1947642080_docx","format":"docx","url":"https://<hidden>/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.zf5l2Biyy0f6P3U72pUxqfuQQbbwJHHgBTJ70yNKqm0","title":"empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.docx","outputformat":65,"outputpath":"output.docx","codepage":46,"delimiter":4,"embeddedfonts":false,"status_info":-81,"nobase64":true}};id=conv_check_1947642080_docx)
[2019-01-15 21:37:41.299] [DEBUG] nodeJS - postProcess (id=conv_check_1947642080_docx)
[2019-01-15 21:37:41.302] [DEBUG] nodeJS - deleteFolderRecursive (id=conv_check_1947642080_docx)

**Comment by benjelloun69** [comment]
anybody here?? =)

**Comment by alexanderonlyoffice** [comment]
@benjelloun69, we apologize for the delayed response. 

If I understand it right, the error you get is on your server B. Please confirm this info.

Please try to check the accessibility of your Nextcloud and Document Server to each other. Execute `wget https://documentserver_address/` from the server with Nextcloud and `wget https://nextcloud_address/` from the server with Document Server.

According to the info you provided, you set JWT secret in config of Nextcloud, did you use the same JWT secret specified in default.json config of the Document Server? Please note that JWT secret and JWT header should be the same on Document Server side and Nextcloud.
