### ISSUE TITLE
Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.0.0.132)

### ISSUE THREAD

**Issue by jbouza** [ONLYOFFICE/onlyoffice-nextcloud#590]
Hello, 
I installing Nexcloud 23 with ONLYOFFICE  7.0.0.132
The example onlyoffice is working with https

![image](https://user-images.githubusercontent.com/24595230/153777485-126334a6-0ebf-40cc-8e3b-84ff8569d5d2.png)

![image](https://user-images.githubusercontent.com/24595230/153777479-f76b4b89-93dc-4b8c-be92-e0ef6cf4150c.png)

but I try connect nextcloud in log register this error

`[2022-02-13T21:46:37.686] [ERROR] nodeJS - error downloadFile:url=https://nextcloud.example.com/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.--yNIqMHopaTeZkUeOo31MB2GcVQxPE0gSWQi3ovVBE;attempt=3;code:null;connect:null;(id=conv_check_1943680295_docx)
Error: Error response: statusCode:503; headers:{"server":"nginx/1.18.0 (Ubuntu)","date":"Sun, 13 Feb 2022 21:46:37 GMT","content-type":"text/html; charset=UTF-8","transfer-encoding":"chunked","connection":"keep-alive","expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","set-cookie":["oc_sessionPassphrase=iAI3eKxDJLq8pBAGLM0OaMAJwjdkLoTgWSbv90V6IntBcvTRzL1xNIXfbsDFJ7B%2Fi72mBkkCdX%2BLogGbhBX1j2rFUEye%2Fu0xk1UVY%2B6R%2BE9hYgLSwCg%2BpUuUqgjWxEMG; path=/; secure; HttpOnly; SameSite=Lax","ocua0snksza7=kallehsb2ol3stvr7o2e213qut; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict"],"content-security-policy":"default-src 'self'; script-src 'self' 'nonce-N3dzWVFCdE1GK0dXeUk4OUlWRmhiNTFjamZ2UmswbFlXY1FReExKRUN1dz06dGx0dGVHZ09RdFh3cGFSMVppVXNPUEF6eHBpVjZnd0phYlIwa05VTlJ0dz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-permitted-cross-domain-policies":"none","x-robots-tag":"none","x-xss-protection":"1; mode=block"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)`

I have installed nextcloud and onlyoffice in differents virtual machine, I using Ubuntu 20.04 in both, and installed onlyoffice by this guide [https://helpcenter.onlyoffice.com/de/installation/docs-community-install-ubuntu.aspx](https://helpcenter.onlyoffice.com/de/installation/docs-community-install-ubuntu.aspx)

**Comment by jbouza** [comment]
I test again change values JWT in local.json and default.json on server onlyoffice
