### ISSUE TITLE
OnlyOffice Docs not Opening

### ISSUE THREAD

**Issue by SushantRathore-Admin** [ONLYOFFICE/onlyoffice-nextcloud#597]

**Comment by SushantRathore-Admin** [comment]
> In that case I'll redirect this issue to people who work with nextcloud

Sure please redirect because we want to put it in productions.

**Comment by SergeyKorneyev** [comment]
Hi @SushantRathore-Admin 
As far as I know, the issue has been fixed on our forum. Could you close it here, if that's the case?

**Comment by wedreamer** [comment]
> 

This causes the request to not be sent, resulting in the requester eventually receiving a timeout exception

```bash
==> /var/log/onlyoffice/documentserver/nginx.error.log <==
2023/09/08 08:52:51 [error] 7045#7045: *71 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.19.0.4, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://127.0.0.1:8000/ConvertService.ashx", host: "onlyoffice"

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2023-09-08T08:53:51.403] [ERROR] [localhost] [conv_check_1368899331_docx] [userId] nodeJS - error downloadFile:url=http://nextcloud.shubuzuo.top:8080/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.ja0BttCk7c97EDL_LBUiDSyAL-DJn6I-wkjHeL3R_SI;attempt=1;code:ETIMEDOUT;connect:undefined Error: Error: whole request cycle timeout
    at raiseError (/snapshot/server/build/server/Common/sources/utils.js)
    at Timeout._onTimeout (/snapshot/server/build/server/Common/sources/utils.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

==> /var/log/onlyoffice/documentserver/nginx.error.log <==
2023/09/08 08:53:58 [error] 7045#7045: *77 upstream timed out (110: Unknown error) while reading response header from upstream, client: 172.19.0.4, server: , request: "POST /ConvertService.ashx HTTP/1.1", upstream: "http://127.0.0.1:8000/ConvertService.ashx", host: "onlyoffice"
```
