### ISSUE TITLE
Error with snapshots Nextcloud/Onlyoffice

### ISSUE THREAD

**Issue by eslijunior** [ONLYOFFICE/onlyoffice-nextcloud#642]
Dear,

I'm sorry if this report is in the wrong place, but I don't know where the problem could be.. if in nextcloud, nextcloud integrator app or in onlyoffice.
I have the compiled version of Onlyoffice (version 7.0.2.0) and I made all the configurations for integration and use in a self-signed certificate environment on the same server.
I can successfully integrate the two, however, I'm having a problem in the nextcloud snapshot routine(tested with AJAX and CRON routines for background on nextcloud). I create a file, modify and save it and the logs in onlyoffice respond well, however when I exit the file an error occurs in a background routine of nextcloud (I believe it is a snapshot routine), causing the changes to the file to disappear (mainly in XLSX files. In DOCX the error occurs, however, the history is preserved);

# Version - DocumentServer(version 7.0.2.0) - Compiled version;
# Version Nextcloud - 24.0.1(After upgrading to this version this routine did not work well);
# Version Nextcloud Onlyoffice Aplication - 7.3.4;
# Ambient: SSL - self-signed - same server.

# Autosave process - Log - Log on Onlyoffice OK
[2022-06-08T08:56:34.261] [INFO] nodeJS - data.type = isSaveLock id = 1168658019
[2022-06-08T08:56:34.262] [DEBUG] nodeJS - isSaveLock: docId = 1168658019; lockRes: true
[2022-06-08T08:56:34.262] [DEBUG] nodeJS - sendData: docId = 1168658019;type = saveLock
[2022-06-08T08:56:34.265] [INFO] nodeJS - data.type = saveChanges id = 1168658019
[2022-06-08T08:56:34.265] [INFO] nodeJS - Start saveChanges docid: 1168658019; reSave: undefined
[2022-06-08T08:56:34.267] [INFO] nodeJS - saveChanges docid: 1168658019 ; deleteIndex: -1 ; startIndex: 0 ; length: 1
[2022-06-08T08:56:34.862] [DEBUG] nodeJS - sendData: docId = 1168658019;type = unSaveLock

# After Close File - Backgroud Snapshot Nextcloud - Log on Onlyoffice - ERROR
...
[2022-06-08T08:58:10.317] [DEBUG] nodeJS - downloadFileFromStorage complete(id=1168658019_789)
[2022-06-08T08:58:10.317] [DEBUG] nodeJS - downloadFileFromStorage list  (id=1168658019_789)
[2022-06-08T08:58:10.468] [DEBUG] nodeJS - AddTask saveFromChanges: docId = 1168658019
[2022-06-08T08:58:12.507] [DEBUG] nodeJS - error spawnAsync(id=1168658019)
Error: ../FileConverter/bin/x2t exited with non-zero code: 86
    at ChildProcess.completionListener (/snapshot/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:43:23)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
    ...
    at spawnAsync (/snapshot/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at ExecuteTask (/snapshot/server/FileConverter/sources/converter.js)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/FileConverter/sources/converter.js
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/FileConverter/node_modules/co/index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2022-06-08T08:58:12.507] [ERROR] nodeJS - stdout (id=1168658019_789):
[2022-06-08T08:58:12.507] [ERROR] nodeJS - stderr (id=1168658019_789):Uncaught TypeError: Cannot read property 'hra' of null
DoctRenderer:<result><error index="-2" /></result>
[2022-06-08T08:58:12.507] [ERROR] nodeJS - ExitCode (code=86;signal=null;error:-86;id=1168658019_789)

 
Where can I investigate this issue? On the nextcloud side, onlyoffice document server side or would it be a bug?
Apparently the integration is correct...only the snapshot/history is not working. Any tips?

Remembering that I've already tested with AuthorizationJwt or Authorization in both onlyoffice and nextcloud...same results.

I edited the config.php file
'onlyoffice' =>
   array(
     'verify_peer_off' => true,
     'jwt_secret' => 'XXXXX',
     'jwt_header' => 'Authorization',
     'allow_local_remote_servers' => true,
   ),

**Comment by eslijunior** [comment]
Problem solved.
 I compiled the current version(7.1.1.0) and error no longer occurs..
