### ISSUE TITLE
Raspberry Pi 4B Installation ONLYOFFICE Error 

### ISSUE THREAD

**Issue by oebta** [ONLYOFFICE/onlyoffice-nextcloud#801]
An exception occurred while downloading the document file to be converted. (Version 7.3.3.49)

docker-compose：

`version: '3'
services:
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    restart: always
    ports:
     - "8088:80"
    environment:
     - JWT_ENABLED=true
     - JWT_SECRET=password
     - JWT_HEADER=AuthorizationJwt
     - JWT_IN_BODY=true
     - USE_UNAUTHORIZED_STORAGE=true
    volumes:
     - '$PWD/logs:/var/log/onlyoffice'
     - '$PWD/data:/var/www/onlyoffice/Data'
     - '$PWD/lib:/var/lib/onlyoffice'
     - '$PWD/db:/var/lib/postgresql'`

[2023-04-07T00:55:30.935] [ERROR] [localhost] [conv_check_2096224471_docx] [userId] nodeJS - error downloadFile:url=https://localhost/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.foIy-XD0OVbgF5nmd5XJu4HUbnWNd4Y-uY7-jfhMjiE;attempt=1;code:undefined;connect:undefined Error: Error response: statusCode:403; headers:{"server":"nginx","date":"Fri, 07 Apr 2023 00:55:30 GMT","content-type":"application/json; charset=utf-8","content-length":"27","connection":"keep-alive","set-cookie":["oc_sessionPassphrase=U8T%2F1tPwAW3UcZp3Av%2FQDMZZ8PFgPHazRc25iLlrkuVX8Z4bThwi9cAugWD2%2F6jEWxN7AOJik7wJU2W%2F6r5%2BfkNH3xXLrRO02TeWE2druY%2BNidKl9FfYREfcy4q4masg; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","oc06zg43ad6f=bj04a6mk9217r7umqni3ei3r05; path=/; secure; HttpOnly; SameSite=Lax"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","pragma":"no-cache","cache-control":"no-cache, no-store, must-revalidate","x-request-id":"ZtOf8SutqDPmRutWrtho","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","x-robots-tag":"noindex, nofollow, noindex,nofollow","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"1; mode=block"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
[2023-04-07T00:55:32.336] [ERROR] [localhost] [conv_check_2096224471_docx] [userId] nodeJS - error downloadFile:url=https://localhost/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.foIy-XD0OVbgF5nmd5XJu4HUbnWNd4Y-uY7-jfhMjiE;attempt=2;code:undefined;connect:undefined Error: Error response: statusCode:403; headers:{"server":"nginx","date":"Fri, 07 Apr 2023 00:55:32 GMT","content-type":"application/json; charset=utf-8","content-length":"27","connection":"keep-alive","set-cookie":["oc_sessionPassphrase=44UrSMgycagpeRnYi67RK99AEf2SEkk28%2FogLmstdHcoZFyzysUVnt5RhzXhOMbcxwtGvfZwg%2FRwuhUfJdn%2FTWe2rZTSOl5LxoDvlHsRfLErjVaEOG4BIeu%2BapP8nP43; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","oc06zg43ad6f=3l1sirge2srn130smt7otlkms3; path=/; secure; HttpOnly; SameSite=Lax"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","pragma":"no-cache","cache-control":"no-cache, no-store, must-revalidate","x-request-id":"Rb3jktipfweGfm42mEjF","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","x-robots-tag":"noindex, nofollow, noindex,nofollow","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"1; mode=block"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
[2023-04-07T00:55:33.698] [ERROR] [localhost] [conv_check_2096224471_docx] [userId] nodeJS - error downloadFile:url=https://localhost/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.foIy-XD0OVbgF5nmd5XJu4HUbnWNd4Y-uY7-jfhMjiE;attempt=3;code:undefined;connect:undefined Error: Error response: statusCode:403; headers:{"server":"nginx","date":"Fri, 07 Apr 2023 00:55:33 GMT","content-type":"application/json; charset=utf-8","content-length":"27","connection":"keep-alive","set-cookie":["oc_sessionPassphrase=LF%2B1DV4olZb1%2BIy1nkW0X4%2BBGJtqgi1wZooLvSDeALIct8VvymKGUBlgzs%2F8E3RI4D1XR3I0lE8Gkxb5SpAKbs9FtzvQ76KWszi9Szlvy3ar%2BcAbICjhHi7SoliJse14; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","oc06zg43ad6f=29nf6cb7ian5tf9d4777fjmikp; path=/; secure; HttpOnly; SameSite=Lax"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","pragma":"no-cache","cache-control":"no-cache, no-store, must-revalidate","x-request-id":"19afVOkvDDKddcLbcIKm","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","x-robots-tag":"noindex, nofollow, noindex,nofollow","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"1; mode=block"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
Flushing stats at  Fri Apr 07 2023 00:56:49 GMT+0000 (Coordinated Universal Time)
{
  counters: {
    'statsd.bad_lines_seen': 0,
    'statsd.packets_received': 0,
    'statsd.metrics_received': 0
  },
  timers: {},
  gauges: {},
  timer_data: {},
  counter_rates: {
    'statsd.bad_lines_seen': 0,
    'statsd.packets_received': 0,
    'statsd.metrics_received': 0
  },
  sets: {},
  pctThreshold: [ 90 ]
}

**Comment by SergeyKorneyev** [comment]
Hello,
According to the logs, the Document Server tries to reach Nextcloud via https://localhost. You need to specify a valid IP address or domain for Nextcloud in the connector's Server settings. You could also try setting a local network address in the Advanced server settings.
