### ISSUE TITLE
Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.5.0.125)

### ISSUE THREAD

**Issue by Liionboy** [ONLYOFFICE/onlyoffice-nextcloud#895]
2023-10-18T21:20:02.975453662Z [2023-10-18T21:20:02.974] [ERROR] [localhost] [conv_check_40834181_docx] [userId] nodeJS - error downloadFile:url=https://nextcloud.orasys-it-solutions.net/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.ZyjalhUzH_72fnucmrcgGqZrAzmmZMdw6ltvRDpfyQ8;attempt=1;code:null;connect:null Error: Error response: statusCode:403; headers:{"date":"Wed, 18 Oct 2023 21:19:40 GMT","content-type":"application/json; charset=utf-8","content-length":"27","connection":"close","set-cookie":["oc_sessionPassphrase=kGW7l6UW%2Fb3WcRlFRsz9n9AQOoLmUQ9OP6d1MaDJzA7x9WCwF9O6udGdNLnnt0jaDqeSBPKI96msTbUOfSiKjaxazxXg7UbeiXNq%2BWbndaRuuUhfoNWLu7Gajkhfz%2BYR; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","oc844eoa8b8q=g1olr0gctko4bha1tuen0ttvea; path=/; secure; HttpOnly; SameSite=Lax"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","pragma":"no-cache","cache-control":"no-cache, no-store, must-revalidate","x-request-id":"dcd2UCmANYx2nPdt2cpt","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","x-robots-tag":"noindex, nofollow, noindex, nofollow","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"1; mode=block","strict-transport-security":"max-age=63072000; preload","cf-cache-status":"DYNAMIC","report-to":"{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=naE7VGlYSxbH3dH2AOZ%2BviJoFJQG6q7BhTLCOF2Bqf2mCs0EiGPDPVUYUj8iQDjCoPsNOapWLOLFc4X8UTElbkfjSmqV9ZS8CnIzseghLVdFOFyNbVha9KliWliGuHzCiIPfEx3LGhHb8DTY%2F%2FgyLD3VzCw%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}","nel":"{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}","server":"cloudflare","cf-ray":"8183d223ef04b9d7-OTP","alt-svc":"h3=\":443\"; ma=86400"};
2023-10-18T21:20:02.975493688Z     at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
2023-10-18T21:20:02.975585703Z     at Request.emit (events.js:400:28)
2023-10-18T21:20:02.975616994Z     at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1066:10)
2023-10-18T21:20:02.975737771Z     at ClientRequest.emit (events.js:400:28)
2023-10-18T21:20:02.975843172Z     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
2023-10-18T21:20:02.975934602Z     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
2023-10-18T21:20:02.976166345Z     at TLSSocket.socketOnData (_http_client.js:515:22)
2023-10-18T21:20:02.976249616Z     at TLSSocket.emit (events.js:400:28)
2023-10-18T21:20:02.976324819Z     at addChunk (internal/streams/readable.js:293:12)
2023-10-18T21:20:02.976407685Z     at readableAddChunk (internal/streams/readable.js:267:9)
2023-10-18T21:20:02.976489203Z     at TLSSocket.Readable.push (internal/streams/readable.js:206:10)

**Comment by crocobc** [comment]
Same problem here with this version.

Downgrade to 7.4 and it's working again.

- Nextcloud and OnlyOffice on the same server behing an haproxy (with ssl offloading).
- No Docker normal install.
- Onlyoffice listening internaly on http.

**Comment by gon3ales** [comment]
Same problem. 
Nextcloud and OnlyOffice on the different servers.
No Docker, deb install.
Onlyoffice listening internaly on https.

**Comment by MichaelHeimann** [comment]
Just had this. Solved it by:
1) get the "secret key" from nextcloud onlyoffice settings page
2) onthe onlyoffice server put the key in /etc/onlyoffice/documentserver/local.json (secrets for inbox, outbox and session)
3) changed "token" for requests (inbox and outbox) and browser in the same file
4) restart nginx (service nginx restart)
5) restart onlyoffice dpkg-reconfigure onlyoffice-documentserver

To me it seems that the config forgot about the secret key. maybe overwritten by an update?

**Comment by crocobc** [comment]
> Just had this. Solved it by:
> 
> 1. get the "secret key" from nextcloud onlyoffice settings page
> 2. on the onlyoffice server put the key in /etc/onlyoffice/documentserver/local.json (secrets for inbox, outbox and session)
> 3. changed "token" for requests (inbox and outbox) and browser in the same file
> 4. restart nginx (service nginx restart)
> 5. restart onlyoffice dpkg-reconfigure onlyoffice-documentserver
> 
> To me it seems that the config forgot about the secret key. maybe overwritten by an update?

Tried that as well same error...

**Comment by MichaelHeimann** [comment]
> > Just had this. Solved it by:
> > 
> > 1. get the "secret key" from nextcloud onlyoffice settings page
> > 2. on the onlyoffice server put the key in /etc/onlyoffice/documentserver/local.json (secrets for inbox, outbox and session)
> > 3. changed "token" for requests (inbox and outbox) and browser in the same file
> > 4. restart nginx (service nginx restart)
> > 5. restart onlyoffice dpkg-reconfigure onlyoffice-documentserver
> > 
> > To me it seems that the config forgot about the secret key. maybe overwritten by an update?
> 
> Tried that as well same error...

What worked for me too (but I didn't like it) was removing the secret key from nextcloud and saving. Does that work for you, maybe?

**Comment by JoeMrCoffee** [comment]
I am having this issue as well - both 7.5 and 7.4 versions of onlyoffice. I tried the version of the plugin in the Nextcloud repo - both Nextcloud 27 and 26 - and also installed the latest 8.2.4 plugin manually extracting and inserting in the custom_apps directory in the Nextcloud container. I think my networking is not allowing for the communication, but it should be on the standard Docker network. 

_Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.5.0.125)_

Onlyoffice Docs address: http://onlyOffice <-- the alias on the Docker container, I know this works because the error will be different I use a bad address.
Secret key set to secret <-- just for testing

I referenced all the documentation, and this is very similar to the reference Docker compose setup except I am using the standard container with apache, not the fpm and routing to the NGINX server. 

Any ideas? 

Docker compose reference:

version: '3'

services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    container_name: nxtclouddb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./SSLdatadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=**********
      - MYSQL_PASSWORD=**********
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud


  app:
    build: ./
    container_name: nxtcloud
    restart: unless-stopped
    ports:
      - 9080:80
      - 8443:443
    links:
      - db
    volumes:
      - ./SSLdata:/var/www/html
    environment:
      - MYSQL_PASSWORD=********
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  onlyOffice:
    image: onlyoffice/documentserver:latest
    ports:
      - 9970:80
    links:
      - app
    container_name: onlyOffice
    environment:
      - JWT_SECRET=secret

**Comment by crocobc** [comment]
Hi there,

Just for information, my problem was not coming from Onlyoffice or Nextcloud.... it was a reverse proxy problem....

I was having a directive in my frontend configuration that was causing the error (403 in the onlyoffice logs)
Culprit Directive in Haproxy was "http-request deny if { hdr_cnt(user-agent) eq 0 }"

If it can help someone...

**Comment by pawankukreja01** [comment]
[One user suggested disabling certificate verification in the Document Server configuration file by setting rejectUnauthorized to false ](https://help.nextcloud.com/t/onlyoffice-error-while-downloading-the-document-file-to-be-converted/45195)[1](https://help.nextcloud.com/t/onlyoffice-error-while-downloading-the-document-file-to-be-converted/45195). You can try this solution and see if it resolves your issue.

**Comment by JoeMrCoffee** [comment]
Thanks for the help - both. I don't have a proxy setup - this is just running or should be running a direct link between the different container services - app for Nextcloud and onlyOffice for Onlyoffice. 

I tried setting the JWT_HEADER in the YAML file as described in the ticket, and also hard coded the credentials in the config/config.php file in the Nextcloud container. Dosen't seem to help. 

I also set the rejectUnauthorized to false. Nothing worked.
"requestDefaults": {
				"headers": {
					"User-Agent": "Node.js/6.13",
					"Connection": "Keep-Alive"
				},
				"gzip": true,
				"rejectUnauthorized": false
			},


I think there is something in the Nextcloud plugin behavior that expects the host IP - in my case localhost, but because I am routing through the Docker network the response or something is not coming through. 

I also notice that if I use the exposed port - 9970 - i.e. http://localhost:9970 then the curl check fails. I even disabled the firewall. At this point I have no idea why it fails. 
Error when trying to connect (cURL error 7: Failed to connect to localhost port 9970 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:9970/healthcheck)

Also what is the difference between the 'ONLYOFFICE Docs address'  and the Advanced options for 'ONLYOFFICE Docs address for internal requests from the server'? Adding the same address in both seems to do nothing.

**Comment by SergeyKorneyev** [comment]
Hello,
Here's some general troubleshooting advice for such issues:
1. Try to avoid using localhost and use IP addresses or domains instead.
2. Check if the Document Server's domain/address is accessible from the Nextcloud server and vice versa.
3. Check if disabling JWT on both sides helps. Information about it can be found here: https://github.com/ONLYOFFICE/onlyoffice-nextcloud?tab=readme-ov-file#configuring-nextcloud-onlyoffice-integration-app
4. If you're using private IP addresses, make sure they are allowed in the Document Server's config: https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#RequestFilteringAgent. Try enabling both the allowPrivateIPAddress and the allowMetaIPAddress parameters.

**Comment by hermann-san** [comment]
@MichaelHeimann  

> What worked for me too (but I didn't like it) was removing the secret key from nextcloud and saving. Does that work for you, maybe?

This also worked for me and I re-added the secret key and it worked again **with** the key.

**Comment by tamer-hassan** [comment]
In the advanced settings before clicking save, set "AuthorizationHeader" to "AuthorizationJwt". worked for me
