### ISSUE TITLE
Upgrade 5.3.0 does not work with SSL 

### ISSUE THREAD

**Issue by Bschalck** [ONLYOFFICE/onlyoffice-nextcloud#91]
Hy ,

I made the update to Onlyoffice docuementserver 5.3.0 .
And yet, it doos not work anymore.
I'm facing a problem with the nginx parameters ( ds-*.conf ) .

Here is my configuration from /etc/nginx/conf.d/ds.conf: 

```
include /etc/nginx/includes/http-common.conf; 
server {
  listen 0.0.0.0:8080 ;
  listen [::]:8080  default_server;
  server_name onlyoffice.devloprog.org ;
  server_tokens off;
  root /usr/share/nginx/html;
  
  ssl on;
    ssl_certificate /etc/letsencrypt/live/onlyoffice.devloprog.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/onlyoffice.devloprog.org/privkey.pem; # managed by Certbot

  add_header Strict-Transport-Security max-age=15768000;

  ssl_session_cache builtin:1000 shared:SSL:10m;
  add_header X-Content-Type-Options nosniff;


  location ~ /.well-known {
     allow all;
  }
include /etc/nginx/includes/ds-*.conf;
}
```

In fact , this can not work with full SSL certificate ( well I do not manage to make it working ). 

My OnlyOffice server  in on Debian stretch.
Listening Port is 8080.
By the way , the link https://onlyoffice.devloprog.org:8080/welcome/ is KO , because of nginx proxypass .

I have few users who are blocked, thanks to react as soon as spossible !

**Comment by osscombat** [comment]
The same issue for 5.3.1 as well. The local.json with "secret" is left intact, but the authentication isn't working.

**Comment by Bschalck** [comment]
Well I corrected my problem by remove all files and conf from onlyoffice and reinstall the package from zero.

**Comment by osscombat** [comment]
I get these in the out.log
```
[2019-06-06T14:40:49.537] [ERROR] nodeJS - error downloadFile:url=https://DOMAIN.NAME/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI$
Error: Error response: statusCode:404 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /index.php/apps/onlyoffice/empty</pre>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
[2019-06-06T14:40:50.567] [ERROR] nodeJS - error downloadFile:url=https://DOMAIN.NAME/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI$
Error: Error response: statusCode:404 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /index.php/apps/onlyoffice/empty</pre>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:250:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
```
